version: '3'

services:
  blazegraph:
    image: lyrasis/blazegraph:2.1.5
    container_name: blazegraph
    ports:
      - "9999:8080"
    volumes:
      - blazegraph_data:/var/blazegraph

  django:
    build: .
    command: gunicorn blazegraph.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - blazegraph
    env_file:
      - .env
      
  nginx:
    build: ./nginx
    image: nginx
    container_name: "nginx_cont"
    ports:
      - 80:80
    depends_on:
      - django_app
volumes:
  blazegraph_data:
